version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/freelec-springboot2-webservice/
    overwrite: yes

# CodeDeploy 에서 ec2 로 넘겨준 파일은 모두 ec2-user 권한 설정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user